// Renders weekly-fixture/data/subscribe-data.json (generated by `npm run generate-docs`).

const VIEWS = {
    all:     { label: 'All' },
    pl:      { label: 'Premier League' },
    club:    { label: 'Seniors' },
    midweek: { label: 'Midweek' },
    juniors: { label: 'Juniors' },
};

// Share the key with index.html so switching pages keeps the active filter.
const ACTIVE_VIEW_KEY = 'fhc.weeklyFixture.activeView';

let data = null;
let activeView = loadActiveView();

function loadActiveView() {
    try {
        const stored = localStorage.getItem(ACTIVE_VIEW_KEY);
        if (stored && Object.prototype.hasOwnProperty.call(VIEWS, stored)) return stored;
    } catch { /* localStorage unavailable */ }
    return 'all';
}

function saveActiveView(view) {
    try { localStorage.setItem(ACTIVE_VIEW_KEY, view); } catch { /* ignore */ }
}

// ─── Boot ────────────────────────────────────────────────────────────

async function load() {
    try {
        const res = await fetch('/data/subscribe-data.json', { cache: 'no-cache' });
        data = await res.json();
    } catch (err) {
        document.getElementById('categoryList').innerHTML =
            `<div class="empty-state">Could not load subscribe data. Run <code>npm run generate-docs</code> first.</div>`;
        return;
    }

    if (!data.categories || data.categories.length === 0) {
        document.getElementById('categoryList').innerHTML =
            `<div class="empty-state">No competitions configured yet.</div>`;
        return;
    }

    if (data.clubName) {
        document.getElementById('pageSubtitle').textContent =
            `Add ${data.clubName} fixtures to your calendar.`;
    }

    renderViewTabs();
    renderActive();
}

// ─── View tabs ───────────────────────────────────────────────────────

function renderViewTabs() {
    const container = document.getElementById('viewTabs');
    container.innerHTML = '';
    for (const [key, cfg] of Object.entries(VIEWS)) {
        const btn = document.createElement('button');
        btn.className = 'view-tab' + (key === activeView ? ' active' : '');
        btn.textContent = cfg.label;
        btn.onclick = () => {
            activeView = key;
            saveActiveView(key);
            renderViewTabs();
            renderActive();
        };
        container.appendChild(btn);
    }
}

// ─── Filtering rules that mirror js/app.js ──────────────────────────

function isPL(name) {
    return /\b(Premier League|PL|PLR)\b/i.test(name);
}

function filteredCategories() {
    const out = [];
    for (const cat of data.categories) {
        // Is this category itself relevant to the active tab?
        const relevant =
            activeView === 'all'
            || (activeView === 'midweek' && cat.key === 'midweek')
            || (activeView === 'juniors' && cat.key === 'juniors')
            || ((activeView === 'pl' || activeView === 'club') && (cat.key === 'mens' || cat.key === 'womens'));

        if (!relevant) continue;

        // Optionally filter the competitions within the category.
        let comps = cat.competitions;
        if (activeView === 'pl')   comps = comps.filter(c => isPL(c.name));
        if (activeView === 'club') comps = comps.filter(c => !isPL(c.name));
        if (comps.length === 0) continue;

        // Only show the category-level "Subscribe to all X" block when the
        // category is being shown in full — otherwise it's misleading.
        const showFull =
            activeView === 'all'
            || (activeView === 'midweek' && cat.key === 'midweek')
            || (activeView === 'juniors' && cat.key === 'juniors');

        out.push({ ...cat, competitions: comps, showFull });
    }
    return out;
}

// ─── Rendering ───────────────────────────────────────────────────────

function renderActive() {
    const subscribeAll = document.getElementById('subscribeAll');
    subscribeAll.innerHTML = '';

    if (activeView === 'all' && data.allCompetitionsEmbedUrl) {
        subscribeAll.appendChild(linkButton(
            data.allCompetitionsEmbedUrl,
            `View all ${data.totalCompetitions} competitions`,
            '📅'
        ));
    }

    const root = document.getElementById('categoryList');
    root.innerHTML = '';

    const cats = filteredCategories();
    if (cats.length === 0) {
        root.innerHTML = `<div class="empty-state">No competitions in this view.</div>`;
        return;
    }

    for (const cat of cats) root.appendChild(renderCategory(cat));
}

function renderCategory(cat) {
    const section = document.createElement('section');
    section.className = 'category';

    const heading = document.createElement('h2');
    heading.className = 'category-heading';
    heading.textContent = cat.label;
    section.appendChild(heading);

    if (cat.showFull && cat.combinedEmbedUrl) {
        section.appendChild(linkButton(cat.combinedEmbedUrl, `View all ${cat.label} fixtures`, '📅'));
    }

    if (cat.showFull && cat.categoryCalendar) {
        section.appendChild(subscribeBlock(
            `Subscribe to all ${cat.label} fixtures`,
            cat.categoryCalendar.publicUrl,
            cat.categoryCalendar.icalUrl
        ));
    }

    for (const comp of cat.competitions) section.appendChild(renderCompetition(comp));
    return section;
}

function renderCompetition(comp) {
    const wrap = document.createElement('article');
    wrap.className = 'comp';

    const h3 = document.createElement('h3');
    h3.className = 'comp-name';
    h3.textContent = comp.name;
    wrap.appendChild(h3);

    const linkRow = document.createElement('div');
    linkRow.className = 'comp-links';

    if (comp.fixtureUrl)     linkRow.appendChild(pillLink(comp.fixtureUrl, '🏑 Fixture'));
    if (comp.competitionUrl) linkRow.appendChild(pillLink(comp.competitionUrl, '🏆 Competition'));
    if (comp.publicUrl)      linkRow.appendChild(pillLink(comp.publicUrl, '📅 Calendar'));

    if (linkRow.children.length > 0) wrap.appendChild(linkRow);

    if (comp.publicUrl || comp.icalUrl) {
        wrap.appendChild(subscribeBlock('Subscribe', comp.publicUrl, comp.icalUrl));
    }

    return wrap;
}

// ─── Shared UI bits ──────────────────────────────────────────────────

/**
 * A prominent link-button (used for "View all X").
 * Visually distinct from subscribe-details: solid accent, external arrow.
 */
function linkButton(href, text, icon = '') {
    const a = document.createElement('a');
    a.className = 'link-button';
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';

    if (icon) {
        const i = document.createElement('span');
        i.className = 'link-button-icon';
        i.textContent = icon;
        a.appendChild(i);
    }

    const label = document.createElement('span');
    label.className = 'link-button-label';
    label.textContent = text;
    a.appendChild(label);

    const arrow = document.createElement('span');
    arrow.className = 'link-button-arrow';
    arrow.textContent = '↗';
    a.appendChild(arrow);

    return a;
}

function pillLink(href, label) {
    const a = document.createElement('a');
    a.className = 'pill';
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';
    a.innerHTML = `${escapeHtml(label)} <span class="pill-arrow" aria-hidden="true">↗</span>`;
    return a;
}

/**
 * A collapsible subscribe instructions block. Visually signalled with
 * "TAP TO EXPAND" copy + an animated caret so it doesn't look like a link.
 */
function subscribeBlock(summaryText, googleUrl, icalUrl) {
    const details = document.createElement('details');
    details.className = 'subscribe-details';

    const sum = document.createElement('summary');

    const label = document.createElement('span');
    label.className = 'summary-label';
    label.textContent = `📲 ${summaryText}`;
    sum.appendChild(label);

    const hint = document.createElement('span');
    hint.className = 'summary-hint';
    hint.textContent = 'Tap';
    sum.appendChild(hint);

    const caret = document.createElement('span');
    caret.className = 'summary-caret';
    caret.setAttribute('aria-hidden', 'true');
    caret.textContent = '▾';
    sum.appendChild(caret);

    details.appendChild(sum);

    const body = document.createElement('div');
    body.className = 'subscribe-body';

    if (googleUrl) {
        body.appendChild(instructionBlock('Google Calendar', [
            'Open the ',
            linkInline(googleUrl, 'Google Calendar link'),
            ' and tap ',
            boldInline('+'),
            ' (mobile) or ',
            boldInline('Add to Google Calendar'),
            ' (desktop).',
        ]));
    }

    if (icalUrl) {
        body.appendChild(instructionBlock('iOS Calendar', [
            'Go to ',
            boldInline('Settings > Calendar > Accounts'),
            ', tap ',
            boldInline('Add Account > Other > Add Subscribed Calendar'),
            ', and paste the ',
            linkInline(icalUrl, 'iCal link'),
            '.',
        ]));
    }

    details.appendChild(body);
    return details;
}

function instructionBlock(title, parts) {
    const block = document.createElement('div');
    block.className = 'instruction';

    const h = document.createElement('div');
    h.className = 'instruction-title';
    h.textContent = title;
    block.appendChild(h);

    const p = document.createElement('p');
    for (const part of parts) {
        if (typeof part === 'string') p.appendChild(document.createTextNode(part));
        else p.appendChild(part);
    }
    block.appendChild(p);
    return block;
}

function linkInline(href, text) {
    const a = document.createElement('a');
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = text;
    return a;
}

function boldInline(text) {
    const s = document.createElement('strong');
    s.textContent = text;
    return s;
}

function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, c => (
        { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
    ));
}

load();
