// Renders weekly-fixture/data/subscribe-data.json (generated by `npm run generate-docs`)
// into a friendlier UI than the markdown version in docs/competitions-mobile.md.

async function load() {
    let data;
    try {
        const res = await fetch('/data/subscribe-data.json', { cache: 'no-cache' });
        data = await res.json();
    } catch (err) {
        document.getElementById('categoryList').innerHTML =
            `<div class="empty-state">Could not load subscribe data. Run <code>npm run generate-docs</code> first.</div>`;
        return;
    }

    if (!data.categories || data.categories.length === 0) {
        document.getElementById('categoryList').innerHTML =
            `<div class="empty-state">No competitions configured yet.</div>`;
        return;
    }

    if (data.clubName) {
        document.getElementById('pageSubtitle').textContent =
            `Add ${data.clubName} fixtures to your calendar.`;
    }

    renderSubscribeAll(data);
    renderCategories(data.categories);
}

// ─── All-competitions quick link ─────────────────────────────────────

function renderSubscribeAll(data) {
    const container = document.getElementById('subscribeAll');
    if (!data.allCompetitionsEmbedUrl) return;

    const link = document.createElement('a');
    link.className = 'big-link';
    link.href = data.allCompetitionsEmbedUrl;
    link.target = '_blank';
    link.rel = 'noopener';
    link.textContent = `📅 View all ${data.totalCompetitions} competitions`;
    container.appendChild(link);
}

// ─── Category sections ───────────────────────────────────────────────

function renderCategories(categories) {
    const root = document.getElementById('categoryList');
    root.innerHTML = '';

    for (const cat of categories) {
        root.appendChild(renderCategory(cat));
    }
}

function renderCategory(cat) {
    const section = document.createElement('section');
    section.className = 'category';

    const heading = document.createElement('h2');
    heading.className = 'category-heading';
    heading.textContent = cat.label;
    section.appendChild(heading);

    if (cat.combinedEmbedUrl) {
        const combined = document.createElement('a');
        combined.className = 'big-link';
        combined.href = cat.combinedEmbedUrl;
        combined.target = '_blank';
        combined.rel = 'noopener';
        combined.textContent = `📅 View all ${cat.label} fixtures`;
        section.appendChild(combined);
    }

    if (cat.categoryCalendar) {
        section.appendChild(subscribeBlock(
            `Subscribe to all ${cat.label} fixtures`,
            cat.categoryCalendar.publicUrl,
            cat.categoryCalendar.icalUrl
        ));
    }

    for (const comp of cat.competitions) {
        section.appendChild(renderCompetition(comp));
    }

    return section;
}

function renderCompetition(comp) {
    const wrap = document.createElement('article');
    wrap.className = 'comp';

    const h3 = document.createElement('h3');
    h3.className = 'comp-name';
    h3.textContent = comp.name;
    wrap.appendChild(h3);

    const linkRow = document.createElement('div');
    linkRow.className = 'comp-links';

    if (comp.fixtureUrl) linkRow.appendChild(pillLink(comp.fixtureUrl, '🏑 Fixture'));
    if (comp.competitionUrl) linkRow.appendChild(pillLink(comp.competitionUrl, '🏆 Competition'));
    if (comp.publicUrl) linkRow.appendChild(pillLink(comp.publicUrl, '📅 Open calendar'));

    if (linkRow.children.length > 0) wrap.appendChild(linkRow);

    if (comp.publicUrl || comp.icalUrl) {
        wrap.appendChild(subscribeBlock('Subscribe', comp.publicUrl, comp.icalUrl));
    }

    return wrap;
}

// ─── Shared UI bits ──────────────────────────────────────────────────

function pillLink(href, label) {
    const a = document.createElement('a');
    a.className = 'pill';
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = label;
    return a;
}

function subscribeBlock(summary, googleUrl, icalUrl) {
    const details = document.createElement('details');
    details.className = 'subscribe-details';

    const sum = document.createElement('summary');
    sum.textContent = `📲 ${summary}`;
    details.appendChild(sum);

    const body = document.createElement('div');
    body.className = 'subscribe-body';

    if (googleUrl) {
        body.appendChild(instructionBlock('Google Calendar', [
            'Open the ',
            linkInline(googleUrl, 'Google Calendar link'),
            ' and tap ',
            boldInline('+'),
            ' (mobile) or ',
            boldInline('Add to Google Calendar'),
            ' (desktop).',
        ]));
    }

    if (icalUrl) {
        body.appendChild(instructionBlock('iOS Calendar', [
            'Go to ',
            boldInline('Settings > Calendar > Accounts'),
            ', tap ',
            boldInline('Add Account > Other > Add Subscribed Calendar'),
            ', and paste the ',
            linkInline(icalUrl, 'iCal link'),
            '.',
        ]));
    }

    details.appendChild(body);
    return details;
}

function instructionBlock(title, parts) {
    const block = document.createElement('div');
    block.className = 'instruction';

    const h = document.createElement('div');
    h.className = 'instruction-title';
    h.textContent = title;
    block.appendChild(h);

    const p = document.createElement('p');
    for (const part of parts) {
        if (typeof part === 'string') p.appendChild(document.createTextNode(part));
        else p.appendChild(part);
    }
    block.appendChild(p);
    return block;
}

function linkInline(href, text) {
    const a = document.createElement('a');
    a.href = href;
    a.target = '_blank';
    a.rel = 'noopener';
    a.textContent = text;
    return a;
}

function boldInline(text) {
    const s = document.createElement('strong');
    s.textContent = text;
    return s;
}

load();
