name: Sync Hockey Victoria Calendars

on:
  schedule:
    # Run daily at 2 AM Melbourne time (adjust as needed)
    - cron: '0 16 * * *'  # 4 PM UTC = 2 AM AEST/3 AM AEDT
  workflow_dispatch:  # Allow manual triggering
    inputs:
      competition:
        description: 'Single competition to process (leave empty to process all)'
        required: false
        type: string
      use_cache:
        description: 'Use cached results from previous runs'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  sync-calendars:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci || npm install
      
      - name: Run calendar sync for all competitions
        if: ${{ github.event.inputs.competition == '' || github.event.inputs.competition == null }}
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          if [[ "${{ github.event.inputs.use_cache }}" == "true" ]]; then
            npm run process-all-competitions -- --all --use-cache
          else
            npm run process-all-competitions -- --all
          fi
      
      - name: Run calendar sync for single competition
        if: ${{ github.event.inputs.competition != '' && github.event.inputs.competition != null }}
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          if [[ "${{ github.event.inputs.use_cache }}" == "true" ]]; then
            npm run process-competition -- "${{ github.event.inputs.competition }}" --use-cache
          else
            npm run process-competition -- "${{ github.event.inputs.competition }}"
          fi
      
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: sync-logs
          path: temp/
          retention-days: 7

  notify-on-failure:
    needs: sync-calendars
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Create issue on failure
        uses: actions/github-script@v7
        with:
          script: |
            const date = new Date().toISOString();
            const runUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Calendar Sync Failed - ${date}`,
              body: `The calendar synchronization workflow failed.\n\n${ context.payload.inputs?.competition ? `Competition: ${context.payload.inputs.competition}\n` : 'Mode: All competitions\n' }Run URL: ${runUrl}\n\nPlease check the logs for more information.`,
              labels: ['bug', 'automated']
            });